In [1]:
#from tensorflow_docs.vis import embed
from tensorflow import keras
#from imutils import paths

#import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np
#import imageio
import cv2
from ipywidgets import Video, Image

import os
import json

Building V2_trailer_Dataset

In [39]:
# # reading the JSON data using json.load()
# file = '/home/app/src/data/shot-type-dataset/v2_full_trailer.json'
# with open(file) as train_file:
#     dict_v2= json.load(train_file)

In [40]:
# Creating a DataFrame with the v2_full_trailer.json"

# dataset = []
# movie = []
# shot= []
# scale_label = []
# scale_val = []
# mov_label = []
# mov_val = []

# # We pass for all JSON keys an append every trailer labels different lists
# for key_movie in dict_v2:
#     for key_shot in dict_v2[key_movie]:

#         dataset.append('v2')
#         movie.append(key_movie)
#         shot.append(key_shot)
#         scale_label.append('None')
#         scale_val.append(int(0))
#         mov_label.append(dict_v2[key_movie][key_shot]['movement']['label'])
#         mov_val.append(dict_v2[key_movie][key_shot]['movement']['value'])

# # We build the dataframe with the lists data
# data = list(zip(dataset, movie, shot, scale_label, scale_val, mov_label, mov_val))  
# columns = ['dataset','movie', 'shot', 'scale_label', 'scale_val', 'move_label', 'move_val']  
        
# dataset_df_v2 = pd.DataFrame(data, columns=columns)

In [41]:
# v2_df = dataset_df_v2
# v2_path = '/home/app/src/data/shot-type-dataset/trailer_v2/'
# v2_df ['video_name'] = v2_path + dataset_df_v2['movie'] + '/'+ 'shot_' + dataset_df_v2['shot'] + '.mp4'
# v2_df = v2_df[['video_name', 'move_label']]
# v2_df = v2_df.rename(columns ={'move_label': 'tag'})

In [2]:
# v2_df.to_csv('/home/app/src/data/CSV/dataset_v2.csv', index = False)

In [4]:
v2_df= pd.read_csv('/home/app/src/CSV/dataset_v2.csv')
v2_df

                                            video_name     tag
0    /home/app/src/data/shot-type-dataset/trailer_v...    Pull
1    /home/app/src/data/shot-type-dataset/trailer_v...    Push
2    /home/app/src/data/shot-type-dataset/trailer_v...    Push
3    /home/app/src/data/shot-type-dataset/trailer_v...    Push
4    /home/app/src/data/shot-type-dataset/trailer_v...    Pull
..                                                 ...     ...
605  /home/app/src/data/shot-type-dataset/trailer_v...    Push
606  /home/app/src/data/shot-type-dataset/trailer_v...  Static
607  /home/app/src/data/shot-type-dataset/trailer_v...  Static
608  /home/app/src/data/shot-type-dataset/trailer_v...  Motion
609  /home/app/src/data/shot-type-dataset/trailer_v...  Motion

[610 rows x 2 columns]

Preparing Trailer_v3_dataset (The complete dataset)

In [43]:
data_df = pd. read_csv('/home/app/src/CSV/dataset_df.csv', dtype={"shot": str})

data_df.drop(columns=['scale_val'], inplace=True)
data_df.drop(columns = ['move_val'], inplace=True)

train_path = '/home/app/src/data/shot-type-dataset/trailer_v3/train/'
data_df['video_name'] = train_path + 'shot_' + data_df['movie'] + '_' + data_df['shot'] + '.mp4'
train_df = data_df[(data_df['dataset']=='train') | (data_df['dataset']=='val') ]
train_df = train_df[['video_name', 'move_label']]
train_df = train_df.rename(columns ={'move_label': 'tag'})


test_path = '/home/app/src/data/shot-type-dataset/trailer_v3/test/'
data_df['video_name'] = test_path + 'shot_' + data_df['movie'] + '_' + data_df['shot'] + '.mp4'
test_df = data_df[data_df['dataset']=='test']
test_df = test_df[['video_name', 'move_label']]
test_df = test_df.rename(columns ={'move_label': 'tag'})

Deleting Multi-movement Tag

In [44]:
train_df = train_df[train_df.tag != 'Multi_movement']
train_df = train_df.reset_index(drop = True) 
test_df = test_df[test_df.tag != 'Multi_movement']
test_df = test_df.reset_index(drop = True)

Finals DFs

In [45]:
train_df

                                              video_name     tag
0      /home/app/src/data/shot-type-dataset/trailer_v...  Static
1      /home/app/src/data/shot-type-dataset/trailer_v...  Static
2      /home/app/src/data/shot-type-dataset/trailer_v...  Static
3      /home/app/src/data/shot-type-dataset/trailer_v...  Static
4      /home/app/src/data/shot-type-dataset/trailer_v...  Static
...                                                  ...     ...
25339  /home/app/src/data/shot-type-dataset/trailer_v...  Static
25340  /home/app/src/data/shot-type-dataset/trailer_v...  Motion
25341  /home/app/src/data/shot-type-dataset/trailer_v...  Static
25342  /home/app/src/data/shot-type-dataset/trailer_v...  Static
25343  /home/app/src/data/shot-type-dataset/trailer_v...    Push

[25344 rows x 2 columns]

In [46]:

test_df

                                             video_name     tag
0     /home/app/src/data/shot-type-dataset/trailer_v...  Static
1     /home/app/src/data/shot-type-dataset/trailer_v...  Static
2     /home/app/src/data/shot-type-dataset/trailer_v...  Static
3     /home/app/src/data/shot-type-dataset/trailer_v...  Static
4     /home/app/src/data/shot-type-dataset/trailer_v...  Motion
...                                                 ...     ...
8144  /home/app/src/data/shot-type-dataset/trailer_v...  Static
8145  /home/app/src/data/shot-type-dataset/trailer_v...  Motion
8146  /home/app/src/data/shot-type-dataset/trailer_v...  Motion
8147  /home/app/src/data/shot-type-dataset/trailer_v...  Static
8148  /home/app/src/data/shot-type-dataset/trailer_v...  Static

[8149 rows x 2 columns]

Reducing Dataset

In [47]:
train_df_bal_static = train_df[train_df.tag == 'Static'][0:320]
train_df_bal_motion = train_df[train_df.tag == 'Motion'][0:320]

len_push_tag = train_df.tag[train_df.tag == 'Push'].shape[0]
len_pull_tag = train_df.tag[train_df.tag == 'Pull'].shape[0]

train_df_bal_push = train_df[train_df.tag == 'Push'][0:len_push_tag-1243]
train_df_bal_pull = train_df[train_df.tag == 'Pull'][0:len_pull_tag]

train_df= pd.concat([train_df_bal_static, train_df_bal_motion, train_df_bal_pull, train_df_bal_push], axis=0)

Mixing the datasets

In [48]:
train_df=train_df.sample(frac=1).reset_index(drop=True)

In [49]:
train_df

                                             video_name     tag
0     /home/app/src/data/shot-type-dataset/trailer_v...  Static
1     /home/app/src/data/shot-type-dataset/trailer_v...    Push
2     /home/app/src/data/shot-type-dataset/trailer_v...  Static
3     /home/app/src/data/shot-type-dataset/trailer_v...    Pull
4     /home/app/src/data/shot-type-dataset/trailer_v...    Pull
...                                                 ...     ...
1185  /home/app/src/data/shot-type-dataset/trailer_v...  Static
1186  /home/app/src/data/shot-type-dataset/trailer_v...  Static
1187  /home/app/src/data/shot-type-dataset/trailer_v...    Push
1188  /home/app/src/data/shot-type-dataset/trailer_v...    Push
1189  /home/app/src/data/shot-type-dataset/trailer_v...    Push

[1190 rows x 2 columns]

In [50]:
test_df_bal_static = test_df[test_df.tag == 'Static'][0:80]
test_df_bal_motion = test_df[test_df.tag == 'Motion'][0:80]

len_push_tag = test_df.tag[test_df.tag == 'Push'].shape[0]
len_pull_tag = test_df.tag[test_df.tag == 'Pull'].shape[0]

test_df_bal_push = test_df[test_df.tag == 'Push'][0:len_push_tag-140]
test_df_bal_pull = test_df[test_df.tag == 'Pull'][0:len_pull_tag]

test_df= pd.concat([test_df_bal_static, test_df_bal_motion, test_df_bal_pull, test_df_bal_push], axis=0)

Mixing the datasets

In [51]:
test_df=test_df.sample(frac=1).reset_index(drop=True)

In [52]:
test_df

                                            video_name     tag
0    /home/app/src/data/shot-type-dataset/trailer_v...  Motion
1    /home/app/src/data/shot-type-dataset/trailer_v...  Motion
2    /home/app/src/data/shot-type-dataset/trailer_v...    Push
3    /home/app/src/data/shot-type-dataset/trailer_v...  Motion
4    /home/app/src/data/shot-type-dataset/trailer_v...  Motion
..                                                 ...     ...
315  /home/app/src/data/shot-type-dataset/trailer_v...    Push
316  /home/app/src/data/shot-type-dataset/trailer_v...    Push
317  /home/app/src/data/shot-type-dataset/trailer_v...    Pull
318  /home/app/src/data/shot-type-dataset/trailer_v...    Pull
319  /home/app/src/data/shot-type-dataset/trailer_v...  Motion

[320 rows x 2 columns]

In [53]:
train_df.to_csv('/home/app/src/CSV/dataset_train_v2+v3_with_rep_shuffle.csv', index = False)
test_df.to_csv('/home/app/src/CSV/dataset_test_v2+v3_with_rep_shuffle.csv', index = False)